.TH "pysusestudio::pysusestudio" 3 "4 Feb 2010" "Version 0.4" "PySuseStudio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysusestudio::pysusestudio \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpySuseStudioError\fP"
.br
.ti -1c
.RI "class \fBAPILimit\fP"
.br
.ti -1c
.RI "class \fBAuthError\fP"
.br
.ti -1c
.RI "class \fBpySuseStudio\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fB__license__\fP = 'GPL v.2 http://www.gnu.org/licenses/gpl.txt'"
.br
.ti -1c
.RI "string \fB__author__\fP = 'Gianluca Urgese <g.urgese@jasone.it>'"
.br
.ti -1c
.RI "string \fB__version__\fP = '0.4'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string \fBpysusestudio::pysusestudio::__author__\fP = 'Gianluca Urgese <g.urgese@jasone.it>'"
.SS "string \fBpysusestudio::pysusestudio::__license__\fP = 'GPL v.2 http://www.gnu.org/licenses/gpl.txt'"
.SS "string \fBpysusestudio::pysusestudio::__version__\fP = '0.4'"
.SH "Author"
.PP 
Generated automatically by Doxygen for PySuseStudio from the source code.
