.TH "pysusestudio::pysusestudio::pySuseStudioError" 3 "4 Feb 2010" "Version 0.4" "PySuseStudio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysusestudio::pysusestudio::pySuseStudioError \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBpysusestudio::pysusestudio::APILimit\fP, and \fBpysusestudio::pysusestudio::AuthError\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fB__str__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmsg\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def pysusestudio::pysusestudio::pySuseStudioError::__init__ ( self,  msg,  error_code = \fCNone\fP)"
.SS "def pysusestudio::pysusestudio::pySuseStudioError::__str__ ( self)"
.PP
Reimplemented in \fBpysusestudio::pysusestudio::APILimit\fP, and \fBpysusestudio::pysusestudio::AuthError\fP.
.SH "Member Data Documentation"
.PP 
.SS "\fBpysusestudio::pysusestudio::pySuseStudioError::msg\fP"
.PP
Reimplemented in \fBpysusestudio::pysusestudio::APILimit\fP, and \fBpysusestudio::pysusestudio::AuthError\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for PySuseStudio from the source code.
