.TH "pysusestudio.py" 3 "4 Feb 2010" "Version 0.4" "PySuseStudio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysusestudio.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpysusestudio::pysusestudio::pySuseStudioError\fP"
.br
.ti -1c
.RI "class \fBpysusestudio::pysusestudio::APILimit\fP"
.br
.ti -1c
.RI "class \fBpysusestudio::pysusestudio::AuthError\fP"
.br
.ti -1c
.RI "class \fBpysusestudio::pysusestudio::pySuseStudio\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpysusestudio::pysusestudio\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBpysusestudio::pysusestudio::__license__\fP = 'GPL v.2 http://www.gnu.org/licenses/gpl.txt'"
.br
.ti -1c
.RI "string \fBpysusestudio::pysusestudio::__author__\fP = 'Gianluca Urgese <g.urgese@jasone.it>'"
.br
.ti -1c
.RI "string \fBpysusestudio::pysusestudio::__version__\fP = '0.4'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PySuseStudio from the source code.
