.TH "pysusestudio::pysusestudio::AuthError" 3 "4 Feb 2010" "Version 0.4" "PySuseStudio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pysusestudio::pysusestudio::AuthError \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpysusestudio::pysusestudio::pySuseStudioError\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fB__str__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmsg\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def pysusestudio::pysusestudio::AuthError::__init__ ( self,  msg)"
.SS "def pysusestudio::pysusestudio::AuthError::__str__ ( self)"
.PP
Reimplemented from \fBpysusestudio::pysusestudio::pySuseStudioError\fP.
.SH "Member Data Documentation"
.PP 
.SS "\fBpysusestudio::pysusestudio::AuthError::msg\fP"
.PP
Reimplemented from \fBpysusestudio::pysusestudio::pySuseStudioError\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for PySuseStudio from the source code.
